"""Model-family adapters for Fisher analysis and graph compilation."""

from .base import (
    ActivationRole,
    ActivationSite,
    AdapterRun,
    AttentionSpec,
    ExecutionPhase,
    FeedForwardSpec,
    LayerBlockBoundaryPlan,
    LayerSpec,
    LengthPolicy,
    MaskPolicy,
    MaskRepresentation,
    ModelAdapter,
    NormalizationCompute,
    NormalizationScale,
    NormalizationSpec,
    PaddingSide,
    ResidualStageKind,
    ResidualStageSpec,
    RopeSpec,
    SegmentRun,
    SegmentSpec,
    SequenceContext,
    SequenceInputOrigin,
    SequenceSpec,
    StructuredOperatorSites,
    TransformerLayerSemantics,
    module_state_fingerprint,
)
from .gemma3 import Gemma3AttentionPrefixRun, Gemma3CausalLMAdapter
from .toy import ToyTransformerAdapter, as_model_adapter

__all__ = [
    "ActivationRole",
    "ActivationSite",
    "AdapterRun",
    "AttentionSpec",
    "ExecutionPhase",
    "FeedForwardSpec",
    "Gemma3AttentionPrefixRun",
    "Gemma3CausalLMAdapter",
    "LayerBlockBoundaryPlan",
    "LayerSpec",
    "LengthPolicy",
    "MaskPolicy",
    "MaskRepresentation",
    "ModelAdapter",
    "NormalizationCompute",
    "NormalizationScale",
    "NormalizationSpec",
    "PaddingSide",
    "ResidualStageKind",
    "ResidualStageSpec",
    "RopeSpec",
    "SegmentRun",
    "SegmentSpec",
    "SequenceContext",
    "SequenceInputOrigin",
    "SequenceSpec",
    "StructuredOperatorSites",
    "TransformerLayerSemantics",
    "ToyTransformerAdapter",
    "as_model_adapter",
    "module_state_fingerprint",
]
